version: '3.4'

services:
  elasticsearch:
    container_name: elasticsearchplugin
    image: docker.io/ultimatedoker/elasticsearch_with_ingest
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
  elasticsearch_grpc_service:
    container_name: elasticgrpc
    image: docker.io/ultimatedoker/elasticsearchgrpcservice
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pwd123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - "C:/Users/ITQ/.aspnet/https:/https"
    depends_on:
      - elasticsearch
    build:
      context: .
      dockerfile: ElasticSearch_gRPC_Service/Dockerfile
  elasticsearch_document_api:
    container_name: elasticapi
    image: docker.io/ultimatedoker/elasticsearchdocumentapi
    ports:
      - "5003:5003"
    depends_on:
      - elasticsearch_grpc_service
      - elasticsearch
    build:
      context: .
      dockerfile: ElasticSearch_Document_API/Dockerfile